#if defined _index_included
  #endinput
#endif

#define _index_included

#include <amxmodx>
#include <reapi>
#include <amxmisc>

#include <competitive/colorchat>
#include <competitive/utils>
#include <competitive/menutils>
#include <competitive/cvars>
#include <competitive/client>

// Modules
#include <competitive/showequip>
#include <competitive/votekick>
#include <competitive/votepause>
#include <competitive/mute>
#include <competitive/roundinfo>
#include <competitive/autoready>
#include <competitive/autodmg>
#include <competitive/afkicker>

// Core
#include <competitive/pugmenu>
#include <competitive/cmd>
#include <competitive/event>
#include <competitive/half>

