#if defined _index_included
  #endinput
#endif

#define _index_included

#include <amxmodx>
#include <amxmisc>
#include <fakemeta>

// Globals
#include <competitive/compatibility>
#include <competitive/globals>
#include <competitive/colorchat>
#include <competitive/cvars>
#include <competitive/utils>
#include <competitive/menutils>
#include <competitive/client>

// Modules
#include <competitive/votekick>
#include <competitive/votepause>
#include <competitive/mute>
#include <competitive/roundinfo>
#include <competitive/autoready>
#include <competitive/autodmg>
#include <competitive/afkicker>
#include <competitive/stats>
#include <competitive/weaprest>
#include <competitive/chooseteam>
#include <competitive/clrates>

// Core
#include <competitive/pugmenu>
#include <competitive/cmd>
#include <competitive/event>
#include <competitive/half>

